apiVersion: v1
kind: ReplicationController
metadata:
  name: joe
spec:
  replicas: 3
  selector:
    app: joe
  template:
    metadata:
      name: joe
      labels:
        app: joe
    spec:
      containers:
        - name: joe
          image: teacherssamko/simple-web:v1
          ports:
            - containerPort: 8000
