apiVersion: batch/v1
kind: Job
metadata:
  name: lion-batch
spec:
  template:
    spec:
      containers:
        - name: lion-batch
          image: teacherssamko/batch-job
      restartPolicy: OnFailure
