apiVersion: v1
kind: ReplicationController
metadata:
  name: lion
spec:
  replicas: 3
  selector:
    app: lion
  template:
    metadata:
      name: lion
      labels:
        app: lion
    spec:
      containers:
        - name: lion
          image: teacherssamko/simple-web:v1
          ports:
            - containerPort: 8000
