apiVersion: batch/v1
kind: Job
metadata:
  name: lion-batch
spec:
  completions: 5
  parallelism: 2
  template:
    spec:
      containers:
        - name: lion-batch
          image: teacherssamko/batch-job:random
      restartPolicy: OnFailure
