apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: joe
  labels:
    app: joe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: joe
  template:
    metadata:
      labels:
        app: joe
    spec:
      containers:
        - name: joe
          image: teacherssamko/simple-web:unhealthy
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 3
