apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: lion
  labels:
    app: lion-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lion-app
  template:
    metadata:
      labels:
        app: lion-app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: lion-app
          image: lion-cr01.kr.ncr.ntruss.com/lion-app:sqlite
          imagePullPolicy: Always
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: lion_app.settings.test
            - name: DJANGO_SECRET_KEY
              value: eosc8@b4w$oz1(9-cusv$gca5td2xs##^plu*q^=08&t@)2=28
          ports:
            - containerPort: 8000
